### PR TITLE
issue#2-trained-model-using-svm-for-vehicles-recognition-using-silhouette

### PR DESCRIPTION
**Pull request by shashigharti**
I have trained a model using SVM to detect vehicles using silhouette. There are 4 vehicles categories: 'van', 'saab', 'bus', 'opel'.

**Steps:**

1. Loading the Data
2. Exploratory Analysis
3. Data Preprocessing (Outlier Removal)
4. Hyperparameter Tuning(GridSearchCV)
5. Data Transformation(StandardScaler, MinMaxScaler)
6. 5 Different Experiments : Training and Testing a classifier (SVM - Support Vector Machine)
     - Without Outlier Removal
     - With Outlier Removal  and Various Data Preprocessing and Parameter Tuning
7. Evaluation

### CODE REVIEW

**Comment by shashigharti** [comment]
Thank you very much! @dzeber for the detailed explanation and suggestions. I will update the new changes based on your suggestions.

**Comment by shashigharti** [comment]
Hi @dzeber, as per your suggestions and change request I have made the following changes and updated the code:
- Applied transformation separately to Test and Train Dataset by passing scaler object to the function.
- Now pairplot image can be zoomed in .
- I have added the description in notebook about why I chose 70/30 Test Train ratio

I will also study and test the ways of using conservative approach of outlier removal

**Comment by shashigharti** [comment]
@dzeber, @mlopatka, I have made changes as per the feedback and its ready for reviewing.
Thank you :) !!

**Comment by dzeber** [comment]
Thanks for resolving these issues!

**Pull request merged**
