### PR TITLE
 Visualization for misclassifications

### LINKED ISSUE #7: [Outreachy applications] Visualization for misclassifications
Misclassifications can reveal a lot about the boundaries of performance of a classifier. Develop a visualization that helps dig into misclassified datapoints in the test set. A simple approach for a binary classifier would be to plot a histogram of the predicted class probabilities across the misclassified test samples in each class.

### PR DESCRIPTION
**Pull request by Sidrah-Madiha**
For this issue fixes #7  , I have defined helper function in Visualization_for_misclassifications.py file
I tested the function on classifier that I have defined in the notebooks vehicles_dataset_classifer_v2 and vehicles_dataset_classifer_v1 (as seen in screenshot and in notebooks as well), please note this visualization does not display correctly predictly class, it displays only the misclassified ones:
v2_visual

 the above screenshot displays the missclassifications for the following confusion matrix,
V2_Confusion

### CODE REVIEW

**Comment by dzeber** [comment]
Very nice! This is a compelling presentation of the confusion matrix.

In fact, it is interesting to see the differences in this plot between the v1 and v2 notebooks. To make this PR even better, why not make this plot for each of the 5 models you evaluated in the v2 notebook so that we can compare them all in the same notebook. Also, it would be nice to add some comments in a text cell with your interpretation of what can be read from the plot.

**Comment by Sidrah-Madiha** [comment]
@dzeber , in v2 notebook (of this PR) I have added an interpretation of the graph, please see attached image
OpelSaab,
in  my PR: https://github.com/mozilla/PRESC/pull/19 I have the same v2 notebook, but for issue #2, I will be incorporating this visualization for all 5 models in that PR for comparative evaluation of all models and then selecting the best. please review this PR and merge.

**Comment by Sidrah-Madiha** [comment]
Hi @dzeber I have restructed helper and notebook files in the branch so that they contain helper files and notebooks for only this task.
I have used black for reformatting code of helper files.
I have implemented "model_false_positive_visualisation" function in allcustommodules.py file that takes in a list of models, training+test data & labels and displays the above graph for each model, please review, looking forward to your feedback.

**Comment by dzeber** [comment]
Thanks for making these updates! The notebook reads very clearly and presents a really nice comparison between the models.

One final thing and it will be ready to merge: similarly to #19, please load your dataset from the relative path in the repo.

**Comment by Sidrah-Madiha** [comment]
Hi @dzeber , I have added relative path for reproducibility in both notebooks v1 and v2.
pathfix

**Pull request merged**
