### PR TITLE
fixed issue #2

### PR DESCRIPTION
**Pull request by ishagarg06**
I worked on winequality dataset. Build the data using various classification model. 
Models used- Decision tree, Random forest regression and Support vector machine
Evaluation is done using confusion matrix and accuracy score.
@dzeber @mlopatka  Please review it once :)
Thanks!

### CODE REVIEW

**Comment by ishagarg06** [comment]
@mlopatka @dzeber Modified the model as per the changes requested for issue#2
--> Path is set for the dataset
--> Quality attribute is discarded.
--> Explained the train-test-split
Please verify it. Thanks!

**Comment by dzeber** [comment]
Thanks for making these updates. One last thing: you don't seem to have used your `winequality_doc.py` module - was this intentional? Ideally you would call those functions and display their outputs in the notebook.

**Comment by ishagarg06** [comment]
@dzeber @mlopatka  Earlier I thought of using `winequality_doc.py` module. But later I called functions and displayed outputs in the notebook itself. If you say I will delete that module.

**Comment by ishagarg06** [comment]
> Thanks for making these updates. One last thing: you don't seem to have used your `winequality_doc.py` module - was this intentional? Ideally you would call those functions and display their outputs in the notebook.

@dzeber @mlopatka Shall I remove that module `winequality_doc.py` or not?

**Comment by dzeber** [comment]
We had requested in the original contribution guidelines that you call the functions from the external module rather than running everything in the notebook. Let's leave it as is at this stage but keep the module for future reference.

**Pull request merged**
