### PR TITLE
For #7: Visualise misclassification

### PR DESCRIPTION
**Pull request by KaairaGupta**
For #7 
I have added a helper function which makes a confusion matrix and calculates percent misclassification per class and plots them.

### CODE REVIEW

**Comment by dzeber** [comment]
This is a great start. I recommend testing this out on an actual model and dataset (you can reuse your work from task #2). When you try it out, think about what action you could take to improve the model based on your visualization. I feel like there is room to dig a little deeper into what information the misclassified examples have.

**Comment by mlopatka** [comment]
@KaairaGupta Please let us know if you intend to continue with this specific PR or if the work here has been integrated into another PR and this can be closed out.

**Comment by KaairaGupta** [comment]
@mlopatka I have made the requested changes and visualised and analysed an actual dataset. PTAL. Thanks

**Comment by mlopatka** [comment]
@KaairaGupta is this work included in another PR that has already been merged in?
It looks like there has been no activity on this specific PR for over a week. 

I'm closing it out now. If this is still work in progress, feel free to reopen and flag me.

**Pull request closed without merging**
