### PR TITLE
For #9: Comparing test sample classifications b/w models

### PR DESCRIPTION
**Pull request by KaairaGupta**
For #9 
- Function `compare_model_classification` added in file `compare_model_classification.py` to plot classification results of two models.
The function takes an input of 2 arrays, one for each model's test samples prediction, and gives visualisation in the form of plots for each class for both the models.

An example run of this function is added under `example_comparision_of_test_samples.ipynb`.

### CODE REVIEW

**Comment by KaairaGupta** [comment]
@dzeber Thank You for the review. I understand that my graphs are not clear and pose trouble in understanding. I will make the changes ASAP.

**Comment by KaairaGupta** [comment]
@dzeber I have made the required changes, please review.
Thanks!

**Comment by KaairaGupta** [comment]
@mlopatka PTAL!
Thanks :)

**Comment by mlopatka** [comment]
@dzeber I see you had some feedback here earlier, can you do a fly-by to see if it is addressed?

**Comment by KaairaGupta** [comment]
@mlopatka Please have a look at this. Waiting for the feedback so that I can make changes before the 30th March

**Comment by KaairaGupta** [comment]
@dzeber please take a look...it has not been reviewed for 12 days
Thanks!

**Pull request merged**
