### PR TITLE
add a conditional metric report notebook

### PR DESCRIPTION
**Pull request by xinrongzhou**

### CODE REVIEW

**Comment by xinrongzhou** [comment]
Hi, David! I have made a notebook example of conditional metrics. Since `conditional metrics` is a function called in `misclass_rate_feature`, I showed the plot by calling the `show_misclass_rates_features`. For the `feature binning` function,  there are not plots. 

Please let me know if there is anything further I need to do.

**Comment by dzeber** [comment]
This is good, thanks! To get this to show up in the report, you also need to add an entry in the [TOC file](https://github.com/mozilla/PRESC/blob/master/presc/report/_toc.yml) under `chapters:`. Add this and see if you're able to run it locally following the steps [here](https://github.com/mozilla/PRESC/blob/master/docs/REPORT.md).

**Comment by xinrongzhou** [comment]
Hi, David! I have added the entry in the TOC file. But when I was following the steps of building the jupyter-book, I got these errors: 
`/Users/zhouxinrong/Desktop/PRESC/presc/report/cond_feature_distr.ipynb:10002: WARNING: Non-consecutive header level increase; 0 to 2`
`/Users/zhouxinrong/Desktop/PRESC/presc/report/conditional_metrics.ipynb:10002: WARNING: Non-consecutive header level increase; 0 to 2`
`/Users/zhouxinrong/Desktop/PRESC/presc/report/misclass_rate.ipynb:10002: WARNING: Non-consecutive header level increase; 0 to 2`

And in the report file, I got this: ( I am going to send you a screenshot through slack).

I have googled this problem but I am still confused. I am not sure if it is because I did something wrong? Thank you so much for your help.  If there is anything I need to work on Please let me know.

**Comment by dzeber** [comment]
Errors were fixed by rebuilding the conda environment

**Pull request merged**
