### PR TITLE
Train test ratio

### PR DESCRIPTION
**Pull request by tab1tha**
This pull request addresses https://github.com/mozilla/PRESC/issues/3

The vehicles.csv dataset is used instead of the generated.csv dataset so that variation could easily be observed. It plots a graph of accuracy against test size and yields a table containing progressive values of performance indices (precision, f1_score, recall), as the test size is changed.

This commit uses modules created in https://github.com/mozilla/PRESC/pull/28 and so it incorporates those changes since the said pull request have not yet been merged to Upstream/master. 
The main file here is train_test_ratio.py which imports the load_dataset and test_size vary modules.
The k_nn module created in the aforementioned issue is modified slightly and imported as part of this solution. The train_test_ratio.ipynb file shows the results obtained by implementing the changes in this pull request.

### CODE REVIEW

**Comment by tab1tha** [comment]
Multi-line comments will be replaced with docstrings, following the recommendations of the maintainer concerning pull request 28, and according to PEP conventions.

**Comment by tab1tha** [comment]
The principal commit is "Effect of split ratio on performance"(sha 599990c). It shows the progressive changes that have been made to address this particular issue #3. 
The first commit was just included so that modules created  before (in pull request #28) can be reused and the second commit was made to synchronize my fork with upstream/master.

**Comment by tab1tha** [comment]
@dzeber @mlopatka Should I continue in this way? that is, reusing the modules I created in the previous pull request for the next?. This will therefore necessitate that the branch of the next pull request will be 'branched out' from this one in order to make these modules available for reuse as I did here.
However, this will pose a problem when the origin branch is updated, because it would not synchronise with this one.
On the other hand, if I treat each pull request independently, I will have to recreate the modules whenever I need them. Considering that I made initial changes to my master branch which are pending in pull request #28, this second option means that I will have to refork upstream and reclone my repo in order that origin master will be in synchrony with upstream master. However, doing this will cause all the unmerged changes in origin master now (#28) to be lost.
Please how do you think I should proceed? what do you recommend?

**Comment by tab1tha** [comment]
@mlopatka please can you merge this? I do not have merging rights.

**Comment by mlopatka** [comment]
@tab1tha apologies for the delay.
Can you please resolve conflicts and ping me for merge.

**Comment by tab1tha** [comment]
@mlopatka I have resolved all the merge conflicts but one. I resolved locally and when I pushed the changes there is one conflict that is present her in k_nn.py
lines 39 to 43 need to be left there while
lines 45 to 47 need to be deleted
However, when I do this on github, the "mark as resolved" button is deactivated so I cannot save the changes. Please can you resolve this last conflict and merge?

**Comment by mlopatka** [comment]
@tab1tha can you verify that knn.py looks good to you?
Then please pull down master so we can use it as a base for resolving other conflicts.

**Pull request merged**
