### PR TITLE
WIP: #2 Train and test a classification model, eeg.csv dataset

### PR DESCRIPTION
**Pull request by arizzogithub**
Hello @dzeber @mlopatka!
Please, receive my appologies for 11 commits - problem with internet. Please, check only this one:
WIP: #2 Train and test a classification model, eeg.csv dataset  017c175
Regards,
Anastasia Rizzo

### CODE REVIEW

**Comment by dzeber** [comment]
Hi @arizzogithub, thank you for your PR! Please note that the project is currently closed to new Outreachy applicants. As we announced in the project Gitter channel last Friday, due to the volume of high-quality contributions we have received, we are no longer considering contributions for Outreachy except for those applicants who have previously opened a PR. You are of course welcome to contribute as a community member, but unfortunately we will not be able to enter you into consideration as an Outreachy candidate.

**Comment by arizzogithub** [comment]
Dear @dzeber ,

Respectfully, but I find what is going on here quite unfair. On the Outreachy website the deadline for this project was set for the 7th of April. Of course we have our chat in Gitter where we all can communicate. Besides the fact of having an official deadline and it is not right to shorten it abruptly; this sudden change of the deadline was not even communicated in this chat with a proper advance notice for us to see it and adjust to it. 

On the evening of the 20th March at 19:35CET, @mlopatka left the message in Gitter that we do not need to worry if we come across a closed issue and it will remain open until otherwise is announced in this channel. At 00:17CET of the 21st of March (i.e. just few hours later), @mlopatka posted "now we are going to close contributions to the repo to anyone who does not already have a PR in flight" - this so with immediate effect!

I started working for this project right away from the start, but nobody and nowhere instructed us that the PR needs to be opened in Github repository right away so early, and that suddenly at some point well before the 7th April deadline, this will no longer be possible and the participation chance would be lost completely. My plan was to complete, open and upload PR, just as I did on the 22nd March, i.e. weeks ahead of the 7th April deadline. Little did I know that you suddenly changed the rules and moved the goalpost with immediate effect. 

It is unthinkable to change the deadline, and to add insult to injury, do this on a Friday-to-Saturday middle of the night, and have the change to be valid with immediate effect without even allowing a couple of days for people to read the change and at least open and submit the PR. Such a major change, should have at least allowed for a reasonable amount of time to see it, make changes, and take actions; even more so during such crazy times of covid-19 with all the sudden difficulties facing us. Personally I also had internet congestion difficulties besides preparations for lockdown etc.

We all understand and respect that you are kindly guiding us with this project and appreciate that you do this over and above your official job. I would appreciate and feel that it would be fair to ask that the sudden and immediate deadline to open the PR can be extended, at least just a couple of days in order to allow people like me who put their heart and soul in this project while coping with everyday life and have a complete ready project, be submitted and not done for nothing without even knowing.

I trust that my request is a reasonable one and while thanking you for your kind time and attention, will be keeping my fingers crossed that you choose to allow it.

**Comment by mlopatka** [comment]
@arizzogithub I completely understand your frustration. Your PR certainly demonstrates a large amount of work. 

Allow me to provide the context for this situation as I understand it.

Given the overwhelming amount of interest in this project @dzeber and I have not been able to review incoming PRs in a timely manner. This led to a longer and longer lag between new submissions and our ability to provide meaningful feedback. We are now operating at a 4-5 day queue based on our current bandwidth to provide reviews (there are over 60 participants active in this project). In order to be mindful of all contributors' efforts we take it very seriously to try and provide feedback on initial PRs so candidates can integrate early feedback and improve upon their work ahead of the final application deadline.

One piece of information missing from your summary of our communication, is the fact that on Thursday, March 12th @dzeber updated the outreachy project page to indicate that this project was *closed* to new applicants. However, looking at the scollback, we failed to publicly announce that for contributors who had already begun work, but not yet submitted a PR. 

That was my mistake.

I understand that if you begun work before March 12th and did not revisit the outreachy page after that, then the announcement on March 20th would seem like a surprise. We have been vocal in the gitter channel regarding the overwhelming volume of excellent contributions.

That being said, I would like to make this situation right and fair to everyone. Therefore, I am going to announce a 2 day extension to new contributors who have outstanding work. Your PR will be reviewed as soon as we can get to it. And you can expect to be considered along with all other candidates when the deadline arrives on April 7th. We had a discussion today with a group of other outreachy mentorship teams to discuss dealing with high volume and will be making subsequent announcements in the gitter channel. 

Thank you for the forthright and honest communication.

**Comment by arizzogithub** [comment]
Dear @dzeber @mlopatka!

Sincere thanks for your swift response and kind understanding of position.  I hope that my appeal has not caused you any inconvenience and appreciate sincerely your action to allow a further extension in this instance. 

Kindest Regards,
Ana

**Pull request merged**
