### PR TITLE
Reorganising a bit and adding two references

### PR DESCRIPTION
**Pull request by alberginia**

### CODE REVIEW

**Comment by dzeber** [comment]
@alberginia Should we also delete the `presc/alberginia` folder, so that it gets moved rather than copied?

**Comment by alberginia** [comment]
I think we need the modules for the misclassification bit. But we can delete the "alberginia" folder and keep the files inside the new "misclassifications" folder.

**Comment by dzeber** [comment]
@alberginia Agreed - so could you delete the `presc/alberginia` from this PR, and then the `presc/misclassifications` will get added when you submit a PR for that work.

**Comment by alberginia** [comment]
@dzeber, I tried to remove the files that @crankycoder moved, as you suggested, but it claims there are complex conflicts that must be resolved. Any idea how to sort it out?

**Comment by dzeber** [comment]
Conflicts are fixed in #180

**Pull request closed without merging**
