### PR TITLE
Compare test sample classifications between models.

### PR DESCRIPTION
**Pull request by tab1tha**
This pull request addresses https://github.com/mozilla/PRESC/issues/9 and https://github.com/mozilla/PRESC/issues/7

Multiple models are trained and tested on the same data set. This pull request gains insights into the prediction confidence of each model by using the predicted class probabilities per model.

This pull request seeks to understand misclassifications too.
knn_proba

The class probabilities per model were plotted.
class_probs

### CODE REVIEW

**Comment by mlopatka** [comment]
@tab1tha is this still a WIP, or ready to review?

**Comment by tab1tha** [comment]
> @tab1tha is this still a WIP, or ready to review?

It's not ready for review yet.

**Comment by tab1tha** [comment]
This pull request is ready for review. @mlopatka @dzeber

**Comment by tab1tha** [comment]
I have discovered that the tendency to predict with very low prediction probabilities is common in data sets with extremely unbalanced classes. As I continue to strudy, I am searching for ways to mitigate the effect of unbalanced classes.

**Pull request merged**
